//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zur.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZREntities : DbContext
    {
        public ZREntities()
            : base("name=ZREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
        public virtual DbSet<tbl_AvalialeVehicles> tbl_AvalialeVehicles { get; set; }
        public virtual DbSet<tbl_BoardingPoints> tbl_BoardingPoints { get; set; }
        public virtual DbSet<tbl_Bookings> tbl_Bookings { get; set; }
        public virtual DbSet<tbl_Cities> tbl_Cities { get; set; }
        public virtual DbSet<tbl_Drivers> tbl_Drivers { get; set; }
        public virtual DbSet<tbl_Employee> tbl_Employee { get; set; }
        public virtual DbSet<tbl_kmcharges> tbl_kmcharges { get; set; }
        public virtual DbSet<tbl_login> tbl_login { get; set; }
        public virtual DbSet<tbl_Ratings> tbl_Ratings { get; set; }
        public virtual DbSet<tbl_RootMaps> tbl_RootMaps { get; set; }
        public virtual DbSet<tbl_Roots> tbl_Roots { get; set; }
        public virtual DbSet<tbl_Statesinfo> tbl_Statesinfo { get; set; }
        public virtual DbSet<tbl_Travelers> tbl_Travelers { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
        public virtual DbSet<tbl_VehiclesInfo> tbl_VehiclesInfo { get; set; }
        public virtual DbSet<tbl_Color> tbl_Color { get; set; }
        public virtual DbSet<tbl_VehicleBrands> tbl_VehicleBrands { get; set; }
        public virtual DbSet<tbl_VehicleType> tbl_VehicleType { get; set; }
        public virtual DbSet<tbl_Eminities> tbl_Eminities { get; set; }
        public virtual DbSet<tbl_Registration> tbl_Registration { get; set; }
        public virtual DbSet<tbl_Orders> tbl_Orders { get; set; }
        public virtual DbSet<tbl_Availabulity> tbl_Availabulity { get; set; }
        public virtual DbSet<tbl_Contact> tbl_Contact { get; set; }
    }
}
