//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zur.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bookings
    {
        public long Id { get; set; }
        public Nullable<long> RootNo { get; set; }
        public string UserName { get; set; }
        public Nullable<long> TravelId { get; set; }
        public Nullable<long> VehicleId { get; set; }
        public Nullable<long> DriverId { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public string Duration { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<double> Fair { get; set; }
        public Nullable<double> Offerdiscount { get; set; }
        public Nullable<int> NoOfseats { get; set; }
        public Nullable<int> ConfirmStatus { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<int> PayStatus { get; set; }
        public string TransactionID { get; set; }
        public string Name { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> JouneyStatus { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string BoardingPoint { get; set; }
        public string DroppingPoint { get; set; }
    }
}
