//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zur.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VehiclesInfo
    {
        public long Id { get; set; }
        public string TravelerUserName { get; set; }
        public Nullable<long> travelId { get; set; }
        public string VehicleNumber { get; set; }
        public string OwnerName { get; set; }
        public string VehicleOwnerCont { get; set; }
        public Nullable<long> RootNumber { get; set; }
        public string Via { get; set; }
        public Nullable<long> DriverId { get; set; }
        public string DriverUserName { get; set; }
        public string DriverNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string VehicleModel { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> SeatsCount { get; set; }
        public Nullable<int> ModelYear { get; set; }
        public string Color { get; set; }
        public string VechileImages { get; set; }
        public string SoruceStartime { get; set; }
        public string Destination { get; set; }
        public string TimeDuration { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public string Source { get; set; }
        public string SourceBoardingPoints { get; set; }
        public string DestinationBoardingPoints { get; set; }
        public string VehicleType { get; set; }
        public string vehicleName { get; set; }
        public string SeatType { get; set; }
        public string Eminities { get; set; }
        public string TermsandConditions { get; set; }
        public long AvailableRootNumber { get; set; }
        public Nullable<bool> ServiceAvailable { get; set; }
        public Nullable<double> SingleWayPrice { get; set; }
        public Nullable<double> TwoWayPrice { get; set; }
        public Nullable<double> RentPerday { get; set; }
        public Nullable<int> TaxPercentage { get; set; }
        public string TravelAgencyName { get; set; }
        public Nullable<int> GST { get; set; }
        public string DropTime { get; set; }
        public Nullable<int> totalDistance { get; set; }
        public string Journeytype { get; set; }
        public Nullable<double> RentPerHour { get; set; }
        public Nullable<double> SelfDriveprice { get; set; }
        public string FuelType { get; set; }
        public string TransmissionType { get; set; }
    }
}
