//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zur.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contact
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string Mobileno { get; set; }
        public string Message { get; set; }
    }
}
