//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zur.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Travelers
    {
        public long ID { get; set; }
        public string TravelName { get; set; }
        public string TavelEmail { get; set; }
        public string TravelPhone { get; set; }
        public string TravelUserName { get; set; }
        public string Address { get; set; }
        public string latitude { get; set; }
        public string Long { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public Nullable<int> vehiclesCount { get; set; }
        public string Travelartype { get; set; }
        public Nullable<double> CommisionPercentage { get; set; }
        public string Logo { get; set; }
        public string Image { get; set; }
        public string VatNo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string State { get; set; }
        public string Landline1 { get; set; }
        public string Landline2 { get; set; }
        public string SecondaryContact { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<double> CommisionPerUser { get; set; }
        public string ContactPersonName { get; set; }
        public string Designation { get; set; }
        public string ConContactnumber { get; set; }
    }
}
