//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zur.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cities
    {
        public long Id { get; set; }
        public string CityName { get; set; }
        public string CityCode { get; set; }
        public Nullable<int> Status { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Stopps { get; set; }
    }
}
