//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zur.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_login
    {
        public long ID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string ContNumber { get; set; }
        public string Pwd { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string Role { get; set; }
        public string Image { get; set; }
    }
}
